# Site settings
title: www.devfuria.com.br
email: feedback@devfuria.com.br
description: "Site de desenvolviemnto web"
-baseurl: "http://www.devfuria.com.br"
baseurl: "http://localhost/devfuria/newsite/_site/"
url: "http://www.devfuria.com.br"

# Build settings
markdown: kramdown
permalink: pretty

host:        0.0.0.0
port:        4000
baseurl:     /devfuria
url:         http://localhost:4000
