# Site settings
title: www.devfuria.com.br
email: flaviomicheletti@hotmail.com
description: "Site de desenvolvimento web"

# Build settings
#markdown: kramdown
markdown: redcarpet
highlighter: pygments
permalink: pretty

exclude: [test-theme.html, readme.md, composer.json, composer.lock, .gitignore]

host: 0.0.0.0
port: 4000

url: http://www.devfuria.com.br
gems:
  - jekyll-sitemap
