# Site settings
title: www.devfuria.com.br
email: feedback@devfuria.com.br
description: "Site de desenvolvimento web"

# Build settings
markdown: kramdown
permalink: pretty

host:        0.0.0.0
port:        4000
