#
# Configurações
#
enable_disqus:    true
enable_analytics: false

# Antes era com kramdown
# markdown:    kramdown
markdown:    redcarpet
highlighter: pygments
permalink:   pretty
#exclude:     [theme, readme.md, composer.json, composer.lock, .gitignore]
gems:
  - jekyll-sitemap

# Para atualizar mais rápido...
exclude: 
    - javascript
#    - php
    - python
    - logica-de-programacao
    - html-css
    - sql
#    - misc
#    - regex
    - tdd
    - git
    - c
    - seguranca-da-informacao
    - linux


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "php"
    values:
      category:
        label: "PHP"
        url:   "/php"
  -
    scope:
      path: "regex"
    values:
      category:
        label: "Expressões Regulares"
        url:   "/regex"