enable_disqus:    false
enable_analytics: false
highlighter: rouge
permalink:   pretty

exclude:
  - node_modules/
  - nbproject/

# for sitemap
_url: http://www.devfuria.com.br

# email
email: "sitedevfuria@gmail.com"

exclude:
    - readme.md
    - composer.*
    - .gitignore
    - tests
    - nbproject
    # - html-css-new
    - backbone
    - c
    - cursos
    - git
    - html-canvas
    - html-css
    - javascript
    - linux
    - logica-de-programacao
    - misc
    - node.js
    - php
    - python
    - regex
    - seguranca-da-informacao
    - sql
    - tdd

defaults:
  -
    scope:
      path: ""
    values:
      layout: "artigo"

