# Site settings
title: www.devfuria.com.br
email: flaviomicheletti@hotmail.com
description: "Site de desenvolvimento web"

# Build settings
#markdown: kramdown
markdown: redcarpet
highlighter: pygments
permalink: pretty
#exclude: [python, logica-de-programacao, tdd, javascript, linux, html-css, regex, misc, git, php, sql, c, seguranca-da-informacao]

exclude: [test-theme.html, readme.md]

host: 0.0.0.0
port: 4000

url: http://www.devfuria.com.br
gems:
  - jekyll-sitemap
