# Site settings
title: www.devfuria.com.br
email: feedback@devfuria.com.br
description: "Site de desenvolvimento web"

# Build settings
#markdown: kramdown
markdown: redcarpet
highlighter: pygments
permalink: pretty
#exclude: [linux, logica-de-programacao, git, python, javascript, php, seguranca-da-informacao, sql, html-css, regex, misc, tdd]

host: 0.0.0.0
port: 4000

gems:
  - jekyll-sitemap
