#
# Configurações
#
enable_disqus:    true
enable_analytics: false

# Antes era com kramdown
# markdown:    kramdown
markdown:    redcarpet
highlighter: pygments
permalink:   pretty
exclude:     [theme, readme.md, composer.json, composer.lock, .gitignore]
gems:
  - jekyll-sitemap

# Para atualizar mais rápido...
#exclude: [javascript, python, logica-de-programacao, tdd, linux, html-css, regex, misc, git, php, sql, c, seguranca-da-informacao]
